dist: xenial
sudo: false

language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3

addons:
  apt:
    packages:
      - xmlsec1

services:
  - mongodb

install:
  - pip install tox
  - pip install tox-travis
  - pip install codecov

script:
  - codecov --version
  - tox

after_success:
  - codecov
